name: Basic Python Check

on: [push, pull_request]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            pip install -r requirements.txt || true

      - name: Import modules
        run: |
            python -c "import main, models, storage, commands, utils, ui; print('Import OK')"
